# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_me_delete(self):
        """
        Test case for me_delete

        
        """
        pass

    def test_me_get(self):
        """
        Test case for me_get

        
        """
        pass

    def test_me_patch(self):
        """
        Test case for me_patch

        
        """
        pass

    def test_projects_get(self):
        """
        Test case for projects_get

        
        """
        pass

    def test_projects_post(self):
        """
        Test case for projects_post

        
        """
        pass

    def test_projects_project_id_access_get(self):
        """
        Test case for projects_project_id_access_get

        
        """
        pass

    def test_projects_project_id_access_post(self):
        """
        Test case for projects_project_id_access_post

        
        """
        pass

    def test_projects_project_id_access_project_access_id_delete(self):
        """
        Test case for projects_project_id_access_project_access_id_delete

        
        """
        pass

    def test_projects_project_id_access_project_access_id_get(self):
        """
        Test case for projects_project_id_access_project_access_id_get

        
        """
        pass

    def test_projects_project_id_access_project_access_id_patch(self):
        """
        Test case for projects_project_id_access_project_access_id_patch

        
        """
        pass

    def test_projects_project_id_activities_activity_id_delete(self):
        """
        Test case for projects_project_id_activities_activity_id_delete

        
        """
        pass

    def test_projects_project_id_activities_activity_id_get(self):
        """
        Test case for projects_project_id_activities_activity_id_get

        
        """
        pass

    def test_projects_project_id_activities_activity_id_patch(self):
        """
        Test case for projects_project_id_activities_activity_id_patch

        
        """
        pass

    def test_projects_project_id_activities_get(self):
        """
        Test case for projects_project_id_activities_get

        
        """
        pass

    def test_projects_project_id_activities_post(self):
        """
        Test case for projects_project_id_activities_post

        
        """
        pass

    def test_projects_project_id_capabilities_delete(self):
        """
        Test case for projects_project_id_capabilities_delete

        
        """
        pass

    def test_projects_project_id_capabilities_get(self):
        """
        Test case for projects_project_id_capabilities_get

        
        """
        pass

    def test_projects_project_id_capabilities_patch(self):
        """
        Test case for projects_project_id_capabilities_patch

        
        """
        pass

    def test_projects_project_id_delete(self):
        """
        Test case for projects_project_id_delete

        
        """
        pass

    def test_projects_project_id_deployments_deployment_target_configuration_id_delete(self):
        """
        Test case for projects_project_id_deployments_deployment_target_configuration_id_delete

        
        """
        pass

    def test_projects_project_id_deployments_deployment_target_configuration_id_get(self):
        """
        Test case for projects_project_id_deployments_deployment_target_configuration_id_get

        
        """
        pass

    def test_projects_project_id_deployments_deployment_target_configuration_id_patch(self):
        """
        Test case for projects_project_id_deployments_deployment_target_configuration_id_patch

        
        """
        pass

    def test_projects_project_id_deployments_get(self):
        """
        Test case for projects_project_id_deployments_get

        
        """
        pass

    def test_projects_project_id_deployments_post(self):
        """
        Test case for projects_project_id_deployments_post

        
        """
        pass

    def test_projects_project_id_domains_domain_id_delete(self):
        """
        Test case for projects_project_id_domains_domain_id_delete

        
        """
        pass

    def test_projects_project_id_domains_domain_id_get(self):
        """
        Test case for projects_project_id_domains_domain_id_get

        
        """
        pass

    def test_projects_project_id_domains_domain_id_patch(self):
        """
        Test case for projects_project_id_domains_domain_id_patch

        
        """
        pass

    def test_projects_project_id_domains_get(self):
        """
        Test case for projects_project_id_domains_get

        
        """
        pass

    def test_projects_project_id_domains_post(self):
        """
        Test case for projects_project_id_domains_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_access_environment_access_id_delete(self):
        """
        Test case for projects_project_id_environments_environment_id_access_environment_access_id_delete

        
        """
        pass

    def test_projects_project_id_environments_environment_id_access_environment_access_id_get(self):
        """
        Test case for projects_project_id_environments_environment_id_access_environment_access_id_get

        
        """
        pass

    def test_projects_project_id_environments_environment_id_access_environment_access_id_patch(self):
        """
        Test case for projects_project_id_environments_environment_id_access_environment_access_id_patch

        
        """
        pass

    def test_projects_project_id_environments_environment_id_access_get(self):
        """
        Test case for projects_project_id_environments_environment_id_access_get

        
        """
        pass

    def test_projects_project_id_environments_environment_id_access_post(self):
        """
        Test case for projects_project_id_environments_environment_id_access_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_activate_post(self):
        """
        Test case for projects_project_id_environments_environment_id_activate_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_activities_activity_id_delete(self):
        """
        Test case for projects_project_id_environments_environment_id_activities_activity_id_delete

        
        """
        pass

    def test_projects_project_id_environments_environment_id_activities_activity_id_get(self):
        """
        Test case for projects_project_id_environments_environment_id_activities_activity_id_get

        
        """
        pass

    def test_projects_project_id_environments_environment_id_activities_activity_id_patch(self):
        """
        Test case for projects_project_id_environments_environment_id_activities_activity_id_patch

        
        """
        pass

    def test_projects_project_id_environments_environment_id_activities_get(self):
        """
        Test case for projects_project_id_environments_environment_id_activities_get

        
        """
        pass

    def test_projects_project_id_environments_environment_id_activities_post(self):
        """
        Test case for projects_project_id_environments_environment_id_activities_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_backup_post(self):
        """
        Test case for projects_project_id_environments_environment_id_backup_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_branch_post(self):
        """
        Test case for projects_project_id_environments_environment_id_branch_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_deactivate_post(self):
        """
        Test case for projects_project_id_environments_environment_id_deactivate_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_delete(self):
        """
        Test case for projects_project_id_environments_environment_id_delete

        
        """
        pass

    def test_projects_project_id_environments_environment_id_get(self):
        """
        Test case for projects_project_id_environments_environment_id_get

        
        """
        pass

    def test_projects_project_id_environments_environment_id_initialize_post(self):
        """
        Test case for projects_project_id_environments_environment_id_initialize_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_merge_post(self):
        """
        Test case for projects_project_id_environments_environment_id_merge_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_patch(self):
        """
        Test case for projects_project_id_environments_environment_id_patch

        
        """
        pass

    def test_projects_project_id_environments_environment_id_routes_get(self):
        """
        Test case for projects_project_id_environments_environment_id_routes_get

        
        """
        pass

    def test_projects_project_id_environments_environment_id_routes_post(self):
        """
        Test case for projects_project_id_environments_environment_id_routes_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_routes_route_id_delete(self):
        """
        Test case for projects_project_id_environments_environment_id_routes_route_id_delete

        
        """
        pass

    def test_projects_project_id_environments_environment_id_routes_route_id_get(self):
        """
        Test case for projects_project_id_environments_environment_id_routes_route_id_get

        
        """
        pass

    def test_projects_project_id_environments_environment_id_routes_route_id_patch(self):
        """
        Test case for projects_project_id_environments_environment_id_routes_route_id_patch

        
        """
        pass

    def test_projects_project_id_environments_environment_id_synchronize_post(self):
        """
        Test case for projects_project_id_environments_environment_id_synchronize_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_variables_get(self):
        """
        Test case for projects_project_id_environments_environment_id_variables_get

        
        """
        pass

    def test_projects_project_id_environments_environment_id_variables_post(self):
        """
        Test case for projects_project_id_environments_environment_id_variables_post

        
        """
        pass

    def test_projects_project_id_environments_environment_id_variables_variable_id_delete(self):
        """
        Test case for projects_project_id_environments_environment_id_variables_variable_id_delete

        
        """
        pass

    def test_projects_project_id_environments_environment_id_variables_variable_id_get(self):
        """
        Test case for projects_project_id_environments_environment_id_variables_variable_id_get

        
        """
        pass

    def test_projects_project_id_environments_environment_id_variables_variable_id_patch(self):
        """
        Test case for projects_project_id_environments_environment_id_variables_variable_id_patch

        
        """
        pass

    def test_projects_project_id_environments_get(self):
        """
        Test case for projects_project_id_environments_get

        
        """
        pass

    def test_projects_project_id_environments_post(self):
        """
        Test case for projects_project_id_environments_post

        
        """
        pass

    def test_projects_project_id_get(self):
        """
        Test case for projects_project_id_get

        
        """
        pass

    def test_projects_project_id_patch(self):
        """
        Test case for projects_project_id_patch

        
        """
        pass

    def test_projects_project_id_settings_delete(self):
        """
        Test case for projects_project_id_settings_delete

        
        """
        pass

    def test_projects_project_id_settings_get(self):
        """
        Test case for projects_project_id_settings_get

        
        """
        pass

    def test_projects_project_id_settings_patch(self):
        """
        Test case for projects_project_id_settings_patch

        
        """
        pass

    def test_projects_project_id_variables_get(self):
        """
        Test case for projects_project_id_variables_get

        
        """
        pass

    def test_projects_project_id_variables_post(self):
        """
        Test case for projects_project_id_variables_post

        
        """
        pass

    def test_projects_project_id_variables_project_variable_id_delete(self):
        """
        Test case for projects_project_id_variables_project_variable_id_delete

        
        """
        pass

    def test_projects_project_id_variables_project_variable_id_get(self):
        """
        Test case for projects_project_id_variables_project_variable_id_get

        
        """
        pass

    def test_projects_project_id_variables_project_variable_id_patch(self):
        """
        Test case for projects_project_id_variables_project_variable_id_patch

        
        """
        pass

    def test_users_get(self):
        """
        Test case for users_get

        
        """
        pass

    def test_users_post(self):
        """
        Test case for users_post

        
        """
        pass

    def test_users_user_id_delete(self):
        """
        Test case for users_user_id_delete

        
        """
        pass

    def test_users_user_id_get(self):
        """
        Test case for users_user_id_get

        
        """
        pass

    def test_users_user_id_patch(self):
        """
        Test case for users_user_id_patch

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
