# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.variableupdate import Variableupdate


class TestVariableupdate(unittest.TestCase):
    """ Variableupdate unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVariableupdate(self):
        """
        Test Variableupdate
        """
        model = swagger_client.models.variableupdate.Variableupdate()


if __name__ == '__main__':
    unittest.main()
