# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.vpn_configuration import VpnConfiguration


class TestVpnConfiguration(unittest.TestCase):
    """ VpnConfiguration unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpnConfiguration(self):
        """
        Test VpnConfiguration
        """
        model = swagger_client.models.vpn_configuration.VpnConfiguration()


if __name__ == '__main__':
    unittest.main()
