# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.git_repository_information import GitRepositoryInformation


class TestGitRepositoryInformation(unittest.TestCase):
    """ GitRepositoryInformation unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGitRepositoryInformation(self):
        """
        Test GitRepositoryInformation
        """
        model = swagger_client.models.git_repository_information.GitRepositoryInformation()


if __name__ == '__main__':
    unittest.main()
