# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.domain_ssl import DomainSSL


class TestDomainSSL(unittest.TestCase):
    """ DomainSSL unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainSSL(self):
        """
        Test DomainSSL
        """
        model = swagger_client.models.domain_ssl.DomainSSL()


if __name__ == '__main__':
    unittest.main()
