# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.redirect_pathupdate import RedirectPathupdate


class TestRedirectPathupdate(unittest.TestCase):
    """ RedirectPathupdate unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedirectPathupdate(self):
        """
        Test RedirectPathupdate
        """
        model = swagger_client.models.redirect_pathupdate.RedirectPathupdate()


if __name__ == '__main__':
    unittest.main()
