# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Domain(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, created_at=None, updated_at=None, project=None, ssl=None, wildcard=None):
        """
        Domain - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'created_at': 'datetime',
            'updated_at': 'datetime',
            'project': 'str',
            'ssl': 'DomainSSL',
            'wildcard': 'bool'
        }

        self.attribute_map = {
            'name': 'name',
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'project': 'project',
            'ssl': 'ssl',
            'wildcard': 'wildcard'
        }

        self._name = name
        self._created_at = created_at
        self._updated_at = updated_at
        self._project = project
        self._ssl = ssl
        self._wildcard = wildcard

    @property
    def name(self):
        """
        Gets the name of this Domain.

        :return: The name of this Domain.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Domain.

        :param name: The name of this Domain.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def created_at(self):
        """
        Gets the created_at of this Domain.

        :return: The created_at of this Domain.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this Domain.

        :param created_at: The created_at of this Domain.
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")

        self._created_at = created_at

    @property
    def updated_at(self):
        """
        Gets the updated_at of this Domain.

        :return: The updated_at of this Domain.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """
        Sets the updated_at of this Domain.

        :param updated_at: The updated_at of this Domain.
        :type: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")

        self._updated_at = updated_at

    @property
    def project(self):
        """
        Gets the project of this Domain.

        :return: The project of this Domain.
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """
        Sets the project of this Domain.

        :param project: The project of this Domain.
        :type: str
        """
        if project is None:
            raise ValueError("Invalid value for `project`, must not be `None`")

        self._project = project

    @property
    def ssl(self):
        """
        Gets the ssl of this Domain.

        :return: The ssl of this Domain.
        :rtype: DomainSSL
        """
        return self._ssl

    @ssl.setter
    def ssl(self, ssl):
        """
        Sets the ssl of this Domain.

        :param ssl: The ssl of this Domain.
        :type: DomainSSL
        """
        if ssl is None:
            raise ValueError("Invalid value for `ssl`, must not be `None`")

        self._ssl = ssl

    @property
    def wildcard(self):
        """
        Gets the wildcard of this Domain.

        :return: The wildcard of this Domain.
        :rtype: bool
        """
        return self._wildcard

    @wildcard.setter
    def wildcard(self, wildcard):
        """
        Sets the wildcard of this Domain.

        :param wildcard: The wildcard of this Domain.
        :type: bool
        """
        if wildcard is None:
            raise ValueError("Invalid value for `wildcard`, must not be `None`")

        self._wildcard = wildcard

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Domain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
