# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DomainSSLupdate(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, chain=None, key=None, certificate=None):
        """
        DomainSSLupdate - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'chain': 'list[str]',
            'key': 'str',
            'certificate': 'str'
        }

        self.attribute_map = {
            'chain': 'chain',
            'key': 'key',
            'certificate': 'certificate'
        }

        self._chain = chain
        self._key = key
        self._certificate = certificate

    @property
    def chain(self):
        """
        Gets the chain of this DomainSSLupdate.

        :return: The chain of this DomainSSLupdate.
        :rtype: list[str]
        """
        return self._chain

    @chain.setter
    def chain(self, chain):
        """
        Sets the chain of this DomainSSLupdate.

        :param chain: The chain of this DomainSSLupdate.
        :type: list[str]
        """
        if chain is None:
            raise ValueError("Invalid value for `chain`, must not be `None`")

        self._chain = chain

    @property
    def key(self):
        """
        Gets the key of this DomainSSLupdate.

        :return: The key of this DomainSSLupdate.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """
        Sets the key of this DomainSSLupdate.

        :param key: The key of this DomainSSLupdate.
        :type: str
        """
        if key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")

        self._key = key

    @property
    def certificate(self):
        """
        Gets the certificate of this DomainSSLupdate.

        :return: The certificate of this DomainSSLupdate.
        :rtype: str
        """
        return self._certificate

    @certificate.setter
    def certificate(self, certificate):
        """
        Sets the certificate of this DomainSSLupdate.

        :param certificate: The certificate of this DomainSSLupdate.
        :type: str
        """
        if certificate is None:
            raise ValueError("Invalid value for `certificate`, must not be `None`")

        self._certificate = certificate

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DomainSSLupdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
