# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GitRepositoryInformation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, url=None, client_ssh_key=None):
        """
        GitRepositoryInformation - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'url': 'str',
            'client_ssh_key': 'str'
        }

        self.attribute_map = {
            'url': 'url',
            'client_ssh_key': 'client_ssh_key'
        }

        self._url = url
        self._client_ssh_key = client_ssh_key

    @property
    def url(self):
        """
        Gets the url of this GitRepositoryInformation.

        :return: The url of this GitRepositoryInformation.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this GitRepositoryInformation.

        :param url: The url of this GitRepositoryInformation.
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")

        self._url = url

    @property
    def client_ssh_key(self):
        """
        Gets the client_ssh_key of this GitRepositoryInformation.

        :return: The client_ssh_key of this GitRepositoryInformation.
        :rtype: str
        """
        return self._client_ssh_key

    @client_ssh_key.setter
    def client_ssh_key(self, client_ssh_key):
        """
        Sets the client_ssh_key of this GitRepositoryInformation.

        :param client_ssh_key: The client_ssh_key of this GitRepositoryInformation.
        :type: str
        """
        if client_ssh_key is None:
            raise ValueError("Invalid value for `client_ssh_key`, must not be `None`")

        self._client_ssh_key = client_ssh_key

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GitRepositoryInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
