# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ProjectSettingsupdate(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, initialize=None, magic_enabled=None):
        """
        ProjectSettingsupdate - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'initialize': 'object',
            'magic_enabled': 'bool'
        }

        self.attribute_map = {
            'initialize': 'initialize',
            'magic_enabled': 'magic_enabled'
        }

        self._initialize = initialize
        self._magic_enabled = magic_enabled

    @property
    def initialize(self):
        """
        Gets the initialize of this ProjectSettingsupdate.

        :return: The initialize of this ProjectSettingsupdate.
        :rtype: object
        """
        return self._initialize

    @initialize.setter
    def initialize(self, initialize):
        """
        Sets the initialize of this ProjectSettingsupdate.

        :param initialize: The initialize of this ProjectSettingsupdate.
        :type: object
        """
        if initialize is None:
            raise ValueError("Invalid value for `initialize`, must not be `None`")

        self._initialize = initialize

    @property
    def magic_enabled(self):
        """
        Gets the magic_enabled of this ProjectSettingsupdate.

        :return: The magic_enabled of this ProjectSettingsupdate.
        :rtype: bool
        """
        return self._magic_enabled

    @magic_enabled.setter
    def magic_enabled(self, magic_enabled):
        """
        Sets the magic_enabled of this ProjectSettingsupdate.

        :param magic_enabled: The magic_enabled of this ProjectSettingsupdate.
        :type: bool
        """
        if magic_enabled is None:
            raise ValueError("Invalid value for `magic_enabled`, must not be `None`")

        self._magic_enabled = magic_enabled

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ProjectSettingsupdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
