# coding: utf-8

"""
    Platform API

    The REST API for Platform.sh.

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RouteRepresentationupdate(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, redirects=None, type=None):
        """
        RouteRepresentationupdate - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'redirects': 'Redirectsupdate',
            'type': 'str'
        }

        self.attribute_map = {
            'redirects': 'redirects',
            'type': 'type'
        }

        self._redirects = redirects
        self._type = type

    @property
    def redirects(self):
        """
        Gets the redirects of this RouteRepresentationupdate.

        :return: The redirects of this RouteRepresentationupdate.
        :rtype: Redirectsupdate
        """
        return self._redirects

    @redirects.setter
    def redirects(self, redirects):
        """
        Sets the redirects of this RouteRepresentationupdate.

        :param redirects: The redirects of this RouteRepresentationupdate.
        :type: Redirectsupdate
        """
        if redirects is None:
            raise ValueError("Invalid value for `redirects`, must not be `None`")

        self._redirects = redirects

    @property
    def type(self):
        """
        Gets the type of this RouteRepresentationupdate.

        :return: The type of this RouteRepresentationupdate.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this RouteRepresentationupdate.

        :param type: The type of this RouteRepresentationupdate.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RouteRepresentationupdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
